version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8086:80"
    volumes:
      - '.:/var/www/html'
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-laravel
      - laravel-database
    networks:
      - backend-net
  laravel-database:
    image: postgres:latest
    container_name: laravel-db
    restart: always
    environment:
      POSTGRES_USER: laravel
      POSTGRES_DB: laravel
      POSTGRES_PASSWORD: laravelpass
    ports:
      - "5474:5432"
      - "5475:5433"
    networks:
     - backend-net
  api-laravel:
    build:
      args:
        user: laraveluser
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    container_name: laravel-api
    working_dir: /var/www/html
    command: >
      sh -c "composer install && php artisan migrate:refresh --seed && php-fpm"
    volumes:
      - .:/var/www/html
    networks:
      - backend-net
networks:
  backend-net:
    driver: bridge